import Head from "next/head";
import "aos/dist/aos.css";
import Image from "next/image";
import Header from "../Components/header";
import Learn from "../Components/blockchain/learn";
import Homepage from "../Components/blockchain/home";
import Features from "../Components/blockchain/features";
import Concept from "../Components/blockchain/concept";
import Navbar from "../Components/navbar";
import Footer from "../Components/footer";
  

export default function Blockchain({blockChain}) {

  const {concept, features, home, learn} = blockChain.document[0];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar />
      <Homepage home={home} />
      <Concept concept={concept}/>
      <Features features={features} />
      <Learn learn={learn}/>
      <Footer />
    </div>
  );
}



import { Appwrite } from "appwrite";

const sdk = new Appwrite();

export const getStaticProps = async () => {
    sdk
      .setEndpoint("http://localhost/v1") // Your API Endpoint
      .setProject("627c0eedb0b99a327ae1"); // Your project ID

    let promise = sdk.database.listDocuments("627c0fbff3a46fe7b4e6");

    let blockChain = await promise;

  return {
    props: {
      blockChain
    },
  };
};
