import Head from "next/head";
import "aos/dist/aos.css";
import Image from "next/image";
import Header from "../Components/header";
import Blogs from "../Components/blogs/blogs";
import Navbar from "../Components/navbar";
import Footer from "../Components/footer";
  

export default function BlogPage({blogData}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar />
      <Blogs blogData={blogData} />
      <Footer />
    </div>
  );
}


import { Appwrite } from "appwrite";

const sdk = new Appwrite();

export const getStaticProps = async () => {
    sdk
      .setEndpoint("http://localhost/v1") // Your API Endpoint
      .setProject("627c0eedb0b99a327ae1"); // Your project ID

    let promise = sdk.database.listDocuments("627c0fbff3a46fe7b4e6");

    let blogData = await promise;

  return {
    props: {
      blogData
    },
  };
};
