import Head from "next/head";
import "aos/dist/aos.css";
import Image from "next/image";
import Header from "../Components/header";
import Blogs from "../Components/blogs/blogs";
import Navbar from "../Components/navbar";
import Footer from "../Components/footer";
import "@fortawesome/fontawesome-svg-core/styles.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar />
      <Blogs />
      <Footer />
    </div>
  );
}
