import Head from "next/head";
import "aos/dist/aos.css";
import Image from "next/image";
import Header from "../Components/header";
import Concept from "../Components/dao/concept";
import Homepage from "../Components/dao/home";
import Features from "../Components/dao/features";
import Navbar from "../Components/navbar";
import Footer from "../Components/footer";
require('dotenv').config({ path: `${__dirname}/../.env` })
import { Appwrite } from "appwrite";


export default function Dao({daoData}) {
  const {concept, features, home} = daoData.document[0];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar />
      <Homepage home={home}/>
      <Concept concept={concept}/>
      <Features features={features} />
      <Footer />
    </div>
  );
}





const sdk = new Appwrite();

export const getStaticProps = async () => {
    sdk
      .setEndpoint("http://localhost/v1") // Your API Endpoint
      .setProject(process.env.PROJECT_ID); // Your project ID

    let dao = sdk.database.listDocuments(process.env.DAO_DB);

    let daoData = await dao;

  return {
    props: {
      daoData
    },
  };
};
