import Head from "next/head";
import "aos/dist/aos.css";
import Image from "next/image";
import date from "date-and-time";
import Header from "../Components/header";
import Navbar from "../Components/navbar";
import Homepage from "../Components/homepage";
import About from "../Components/about";
import Highlight from "../Components/highlight";
import News from "../Components/news";
import Footer from "../Components/footer";
require('dotenv').config({ path: `${__dirname}/../.env` })
import { Appwrite } from "appwrite";



export default function Home({ homeData, news }) {
  // console.log(data);
  // console.log(news);
  // console.log(date.format(new Date(), 'YYYY-MM-DD', true));
  const { home, about, highlight } = homeData.document[0];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar />
      <Homepage />
      <About about={about}/>
      <Highlight />
      <News newsData={news} />
      <br />
      <Footer />
    </div>
  );
}



const sdk = new Appwrite();

export const getStaticProps = async () => {
    sdk
      .setEndpoint("http://localhost/v1") // Your API Endpoint
      .setProject(process.env.PROJECT_ID); // Your project ID

    let promise = sdk.database.listDocuments(process.env.INDEX_DB);

    let homeData = await promise;

  const newsapi = await fetch(
    "https://newsapi.org/v2/everything?q=web3&from=" +
      date.format(new Date(), "YYYY-MM-DD", true) +
      "&sortBy=publishedAt&apiKey=ac33785863764469b3c8efb55b183743"
  );
  const news = await newsapi.json();

  const coinpriceapi = await fetch(
    "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false"
  );
  const coinprice = await coinpriceapi.json();

  return {
    props: {
      homeData,
      news,
      coinprice,
    },
  };
};
