import Head from "next/head";
import "aos/dist/aos.css";
import Image from "next/image";
import Header from "../Components/header";
import Navbar from "../Components/navbar";
import Homepage from "../Components/homepage";
import About from "../Components/about";
import Highlight from "../Components/highlight";
import News from "../Components/news";
import Footer from "../Components/footer";
  

export default function Home({data}) {
  // console.log(data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar />
      <Homepage />
      <About />
      <Highlight />
      <News />
      <Footer />
    </div>
  );
}

// import { Appwrite } from "appwrite";


// const sdk = new Appwrite();

// export const getStaticProps = async () => {
//   sdk
//     .setEndpoint("http://localhost/v1") // Your API Endpoint
//     .setProject("627c0eedb0b99a327ae1"); // Your project ID

//   let promise = sdk.database.listDocuments("627c1203b0d457d95d8f");

//   let data = await promise;
//   console.log("data", data);
// return{
//   props: {
//   data
//   }
// }

// };
