import Head from "next/head";
import "aos/dist/aos.css";
import Image from "next/image";
import Header from "../Components/header";
import Learn from "../Components/nft/learn";
import Homepage from "../Components/nft/home";
import Popularnfts from "../Components/nft/popular";
import Navbar from "../Components/navbar";
import Footer from "../Components/footer";
  

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar />
      <Homepage />
      <Learn />
      <Popularnfts />
      <Footer />
    </div>
  );
}
